import { TranslationObjectType } from './ua'

export const en: TranslationObjectType = {
  login: 'Log in',
  loginTitle: 'Log in',
  email: 'Email',
  password: 'Password',
  passwordConfirm: 'Confirm password',
  signUpTitle: 'Registration',
  signUp: 'Sign Up',
  firstName: 'First Name',
  lastName: 'Last Name',
  profile: 'Profile',
  en: 'en',
  ua: 'ua',
  apply: 'Apply',
  code: 'Code',
  emailConfirm: 'Email confirmation',
  confirm: 'Confirm',
  back: 'Back',
  invalidCode: 'Invalid code',
  incorrectCreds: 'Incorrect username or password.',
  emailTaken: 'User with this email already exists',
  addAnimal: 'Create animal',
  description: 'Description',
  name: 'Name',
  imageUrl: 'Image URL',
  age: 'Age',
  weight: 'Weight',
  height: 'Height',
  status: 'Current status',
  phone: 'Phone',
  jobPosition: 'Job position',
  save: 'Save',
  address: 'Address',
  title: 'Title',
  choose: 'Choose',
  gender: 'Gender',
  color: 'Color',
  animalType: 'Type',
  sterilized: 'Sterilized',
  updateAnimal: 'Save',
  removeAnimal: 'Remove animal',
  removeAnimalText: 'Are you sure that you want to remove animal?',
  cancel: 'Cancel',
  changeUserRole: 'Change user role',
  removeUserFromShelter: 'Remove user from shelter',
  removeUserFromShelterText: 'Are you sure that you want to remove user?',
  manageShelter: 'Manage shelter',
  shelterUsers: 'Shelter users',
  role: 'Role',
  changeRole: 'Change role',
  user: 'User',
  inviteUser: 'Invite user',
  invite: 'Invite',
  shelterWorkers: 'Shelter workers',
  backToShelter: 'Back to shelter',
}

export const localeEn = 'en'
