export const ua = {
  login: 'Увійти',
  loginTitle: 'Вхід',
  email: 'Email',
  password: 'Пароль',
  passwordConfirm: 'Підтвердіть пароль',
  signUpTitle: 'Реєстрація',
  signUp: 'Зареєструватись',
  firstName: "Ім'я",
  lastName: 'Прізвище',
  profile: 'Профіль',
  en: 'en',
  apply: 'Застосувати',
  ua: 'ua',
  code: 'Код',
  emailConfirm: 'Підтвердження email',
  confirm: 'Підтвердити',
  back: 'Назад',
  invalidCode: 'Невірний код',
  incorrectCreds: 'Невірний логін або пароль.',
  emailTaken: 'Користувач з таким Email вже існує.',
  addAnimal: 'Зареєструвати тварину',
  description: 'Опис',
  name: "Ім'я",
  imageUrl: 'Посилання на фото',
  age: 'Вік',
  weight: 'Вага',
  height: 'Зріст',
  status: 'Статус',
  phone: 'Номер телефону',
  jobPosition: 'Посада',
  save: 'Зберегти',
  address: 'Адреса',
  title: 'Назва',
  choose: 'Оберіть',
  gender: 'Стать',
  color: 'Колір',
  animalType: 'Вид',
  sterilized: 'Стерилізований(а)',
  updateAnimal: 'Зберегти',
  removeAnimal: 'Видалити тварину',
  removeAnimalText: 'Ви впевнені, що бажаєте видалити тварину?',
  cancel: 'Ні',
  changeUserRole: 'Змінити роль користувача',
  removeUserFromShelter: 'Видалити користувача',
  removeUserFromShelterText: 'Ви впевнені, що бажаєте видалити користувача?',
  manageShelter: 'Управління Притулком',
  shelterUsers: 'Співробітники притулку',
  role: 'Роль',
  changeRole: 'Змінити роль',
  user: 'Користувач',
  inviteUser: 'Запросити користувача',
  invite: 'Запросити',
  shelterWorkers: 'Співробітники',
  backToShelter: 'Назад до притулку',
}

const keys = Object.keys(ua) as Array<keyof typeof ua>

export type TranslationKeys = typeof keys[number]
export type TranslationObjectType = typeof ua

export const localeUa = 'ua'
